[target.x86_64-unknown-linux-musl]
rustflags = [
	"-C", "target-feature=+crt-static"
]

[alias]
acl = ["bin", "cargo-acl"]
deny = ["bin", "cargo-deny"]
make = ["bin", "cargo-make"]
vet = ["bin", "cargo-vet"]
